/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package examples;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3597057431170025071L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockInfo\",\"namespace\":\"examples\",\"fields\":[{\"name\":\"Symbol\",\"type\":\"string\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Currency\",\"type\":\"string\"},{\"name\":\"Price\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockInfo> ENCODER =
      new BinaryMessageEncoder<StockInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockInfo> DECODER =
      new BinaryMessageDecoder<StockInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockInfo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Symbol;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence Currency;
  @Deprecated public java.lang.CharSequence Price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockInfo() {}

  /**
   * All-args constructor.
   * @param Symbol The new value for Symbol
   * @param Name The new value for Name
   * @param Currency The new value for Currency
   * @param Price The new value for Price
   */
  public StockInfo(java.lang.CharSequence Symbol, java.lang.CharSequence Name, java.lang.CharSequence Currency, java.lang.CharSequence Price) {
    this.Symbol = Symbol;
    this.Name = Name;
    this.Currency = Currency;
    this.Price = Price;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Symbol;
    case 1: return Name;
    case 2: return Currency;
    case 3: return Price;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Symbol = (java.lang.CharSequence)value$; break;
    case 1: Name = (java.lang.CharSequence)value$; break;
    case 2: Currency = (java.lang.CharSequence)value$; break;
    case 3: Price = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Symbol' field.
   * @return The value of the 'Symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return Symbol;
  }


  /**
   * Sets the value of the 'Symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.Symbol = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }


  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Currency' field.
   * @return The value of the 'Currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return Currency;
  }


  /**
   * Sets the value of the 'Currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.Currency = value;
  }

  /**
   * Gets the value of the 'Price' field.
   * @return The value of the 'Price' field.
   */
  public java.lang.CharSequence getPrice() {
    return Price;
  }


  /**
   * Sets the value of the 'Price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.CharSequence value) {
    this.Price = value;
  }

  /**
   * Creates a new StockInfo RecordBuilder.
   * @return A new StockInfo RecordBuilder
   */
  public static examples.StockInfo.Builder newBuilder() {
    return new examples.StockInfo.Builder();
  }

  /**
   * Creates a new StockInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockInfo RecordBuilder
   */
  public static examples.StockInfo.Builder newBuilder(examples.StockInfo.Builder other) {
    if (other == null) {
      return new examples.StockInfo.Builder();
    } else {
      return new examples.StockInfo.Builder(other);
    }
  }

  /**
   * Creates a new StockInfo RecordBuilder by copying an existing StockInfo instance.
   * @param other The existing instance to copy.
   * @return A new StockInfo RecordBuilder
   */
  public static examples.StockInfo.Builder newBuilder(examples.StockInfo other) {
    if (other == null) {
      return new examples.StockInfo.Builder();
    } else {
      return new examples.StockInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockInfo>
    implements org.apache.avro.data.RecordBuilder<StockInfo> {

    private java.lang.CharSequence Symbol;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence Currency;
    private java.lang.CharSequence Price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(examples.StockInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Symbol)) {
        this.Symbol = data().deepCopy(fields()[0].schema(), other.Symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Currency)) {
        this.Currency = data().deepCopy(fields()[2].schema(), other.Currency);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Price)) {
        this.Price = data().deepCopy(fields()[3].schema(), other.Price);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing StockInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(examples.StockInfo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.Symbol)) {
        this.Symbol = data().deepCopy(fields()[0].schema(), other.Symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Currency)) {
        this.Currency = data().deepCopy(fields()[2].schema(), other.Currency);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Price)) {
        this.Price = data().deepCopy(fields()[3].schema(), other.Price);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'Symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return Symbol;
    }


    /**
      * Sets the value of the 'Symbol' field.
      * @param value The value of 'Symbol'.
      * @return This builder.
      */
    public examples.StockInfo.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Symbol' field has been set.
      * @return True if the 'Symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Symbol' field.
      * @return This builder.
      */
    public examples.StockInfo.Builder clearSymbol() {
      Symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }


    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public examples.StockInfo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public examples.StockInfo.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return Currency;
    }


    /**
      * Sets the value of the 'Currency' field.
      * @param value The value of 'Currency'.
      * @return This builder.
      */
    public examples.StockInfo.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Currency = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Currency' field has been set.
      * @return True if the 'Currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Currency' field.
      * @return This builder.
      */
    public examples.StockInfo.Builder clearCurrency() {
      Currency = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Price' field.
      * @return The value.
      */
    public java.lang.CharSequence getPrice() {
      return Price;
    }


    /**
      * Sets the value of the 'Price' field.
      * @param value The value of 'Price'.
      * @return This builder.
      */
    public examples.StockInfo.Builder setPrice(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Price' field has been set.
      * @return True if the 'Price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Price' field.
      * @return This builder.
      */
    public examples.StockInfo.Builder clearPrice() {
      Price = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockInfo build() {
      try {
        StockInfo record = new StockInfo();
        record.Symbol = fieldSetFlags()[0] ? this.Symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Currency = fieldSetFlags()[2] ? this.Currency : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Price = fieldSetFlags()[3] ? this.Price : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockInfo>
    READER$ = (org.apache.avro.io.DatumReader<StockInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.Symbol);

    out.writeString(this.Name);

    out.writeString(this.Currency);

    out.writeString(this.Price);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Symbol = in.readString(this.Symbol instanceof Utf8 ? (Utf8)this.Symbol : null);

      this.Name = in.readString(this.Name instanceof Utf8 ? (Utf8)this.Name : null);

      this.Currency = in.readString(this.Currency instanceof Utf8 ? (Utf8)this.Currency : null);

      this.Price = in.readString(this.Price instanceof Utf8 ? (Utf8)this.Price : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Symbol = in.readString(this.Symbol instanceof Utf8 ? (Utf8)this.Symbol : null);
          break;

        case 1:
          this.Name = in.readString(this.Name instanceof Utf8 ? (Utf8)this.Name : null);
          break;

        case 2:
          this.Currency = in.readString(this.Currency instanceof Utf8 ? (Utf8)this.Currency : null);
          break;

        case 3:
          this.Price = in.readString(this.Price instanceof Utf8 ? (Utf8)this.Price : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










